Anpassungen der Doku aus Feedback in LV
Lammer-FH/boutique-hotel-technikum-2024-ae pull request #17
Opened 2024-06-01 08:06 UTC by StroSte

closes #7

2024-06-01 08:08 UTC, StroSte commented
Noch offene Punkte:
- [ ] Filterung auf /rooms passieren soll oder auf /rooms/{id}
- [ ] PUT api/v1/bookings/{id} <- 200
- [ ] DELETE api/v1/bookings/{id} <- 200
- [ ] Paperprototype<: noch alles (Kein Zugang)

2024-06-01 12:52 UTC, lukasfoidl requested changes
I would add the filter option to both, all rooms and one specific room to request all rooms available in a specific time frame and check one specific room for availability if necessary. If our supervirsor wishes the use of the filter keyword please use it. 

I don't see any reason in the user stories to have a put and delete endpoint on bookings, why is it in the ticket description actually?

Please add the paper prototype changes as well.

2024-06-01 12:52 UTC, lukasfoidl commented on api_specification.yaml
> +  /rooms:
/api/v1/rooms or add in info the standard path

2024-06-01 12:52 UTC, lukasfoidl commented on api_specification.yaml
> +  /rooms/{id}:
/api/v1/rooms/{id} or add in info the standard path

2024-06-01 12:52 UTC, lukasfoidl commented on api_specification.yaml
> +  /booking:
/api/v1/bookings (plural) or add in info the standard path

2024-06-01 12:57 UTC, StroSte commented
@se23m044 just added the updated paperprototype

2024-06-02 09:39 UTC, lukasfoidl requested changes

2024-06-02 09:39 UTC, lukasfoidl commented on api_specification.yaml
> +        401:
Please add 404 error if no rooms found in the specified date range.

2024-06-03 18:19 UTC, lukasfoidl approved these changes

2024-06-03 18:20 UTC, merged