added API specification
Lammer-FH/boutique-hotel-technikum-2024-ae pull request #4
Opened 2024-05-11 09:31 UTC by lukasfoidl

2024-05-11 09:42 UTC, StroSte requested changes
Schaut schon gut aus nur ein paar Kleinigkeiten

2024-05-11 09:42 UTC, StroSte commented on API_specification.md
> +
Request Params für pagination fehlen

2024-05-11 09:42 UTC, StroSte commented on API_specification.md
> +            "description": "Großes helles Zimmer mit wetseitigem Balkon...",
typo: westseitigem

2024-05-11 09:42 UTC, StroSte commented on API_specification.md
> +    "description": "Großes helles Zimmer mit wetseitigem Balkon...",
typo: westseitigem

2024-05-11 09:42 UTC, StroSte commented on API_specification.md
> +            "description": "Großes helles Zimmer mit wetseitigem Balkon...",
typo: westseitigem

2024-05-11 09:42 UTC, StroSte commented on API_specification.md
> +    "room":
Brauchen wir die Info wirklich?Das haben wir ja eigentlich schon im Frontend (potenziell im LocalStorage) über vorhergehende API-Requests

2024-05-11 09:42 UTC, StroSte commented on API_specification.md
> +## `GET: /rooms`
Wollen wir hier auch die Verfügbarkeit gleich optional abfragen lassen?

2024-05-11 10:02 UTC, lukasfoidl commented on API_specification.md
> +## `GET: /rooms`
Hier werden alle Rooms abgefragt für eine Übersicht. Laut US3 soll nur "ein bestimmtes Zimmer zum meinem gewünschten Reisezeitraum" die Verfügbarkeit abgefragt werden. Daher würde ich das hier nicht hinzunehmen.

2024-05-11 10:02 UTC, lukasfoidl commented on API_specification.md
> +    "room":
Guter Punkt, aber ist sicher einfacher für das MVP erstmal direkt den Room wieder mitzuschicken und Performanceverbesserungen für spätere Releases aufzuheben. Bei 100 Besuchern pro Tag auch Overhead meiner Meinung nach.

2024-05-11 10:40 UTC, StroSte requested changes

2024-05-11 10:40 UTC, StroSte commented on API_specification.md
Im ganzen Dokument fehlt mir aktuell noch die Status codes, also dass die jeweiligen Response Schemas bei HTTP 200 zurückkommen.

Sonst passt das sehr gut :)

2024-05-14 19:35 UTC, StroSte approved these changes
Passt, sehr gute Arbeit :)

2024-05-14 19:38 UTC, merged