Added DB Design
Lammer-FH/boutique-hotel-technikum-2024-ae pull request #5
Opened 2024-05-11 10:31 UTC by StroSte

closes #2

2024-05-11 15:04 UTC, lukasfoidl requested changes
Bitte die Namings ausbessern wie angemerkt und beim Ändern von Ids nicht auf die Namen der FKs vergessen.
Sonst ein paar Kleinigkeiten aber gute Arbeit.

2024-05-11 15:04 UTC, lukasfoidl commented on db-design.md
> +| RoomImageId | Int          | no   | autoincrement | PK                                   |
Wieso nicht einfach `Id`, dann bleibt es simple in dieser Tabelle?

2024-05-11 15:04 UTC, lukasfoidl commented on db-design.md
> +| RoomId      | Int          | no   | autoincrement | PK                    |
Wieso nicht einfach `Id`, dann bleibt es simple in dieser Tabelle?

2024-05-11 15:04 UTC, lukasfoidl commented on db-design.md
> +| RoomId      | Int          | no   | null          | FK Rooms.RoomId                      |
Wie kann das Feld nicht nullable aber initial null sein?

2024-05-11 15:04 UTC, lukasfoidl commented on db-design.md
> +| CharacteristicId | Int         | no   | autoincrement | PK          |
Wieso nicht einfach `Id`, dann bleibt es simple in dieser Tabelle?

2024-05-11 15:04 UTC, lukasfoidl commented on db-design.md
> +| GuestId      | Int          | no       | autoincrement | PK                               |
Wieso nicht einfach `Id`, dann bleibt es simple in dieser Tabelle?

2024-05-11 15:04 UTC, lukasfoidl commented on db-design.md
> +| CharacteristicId | Int  | no       | null    | FK Characteristics.CharacteristicId |
Wie kann das Feld nicht nullable aber initial null sein?
Bitte noch hinzufügen, dass sie gemeinsam den PK repräsentieren.

2024-05-11 15:04 UTC, lukasfoidl commented on db-design.md
> +| BookingId     | Int         | no       | autoincrement | PK                                                          |
Wieso nicht einfach `Id`, dann bleibt es simple in dieser Tabelle?

2024-05-11 15:04 UTC, lukasfoidl commented on db-design.md
> +| BookingNumber | VarChar(64) | no       |               | UniqueKey, number of a booking for communication with guest |
Sollen wir wirklich eine Nummer als String in der DB speichern?

2024-05-11 15:04 UTC, lukasfoidl commented on db-design.md
> +| GuestId       | Int         | no       |               |                                                             |
FK fehlt

2024-05-11 15:04 UTC, lukasfoidl commented on db-design.md
> +| RoomId    | Int  | no       |         | FK Rooms.RoomId       |
Bitte noch hinzufügen, dass sie gemeinsam den PK repräsentieren.

2024-05-11 15:04 UTC, lukasfoidl commented on db-design.md
> +| Name             | VarChar(64) | yes  | null          |             |
Macht ein Merkmal ohne Namen wirklich Sinn?

2024-05-14 16:45 UTC, StroSte commented on db-design.md
> +| BookingNumber | VarChar(64) | no       |               | UniqueKey, number of a booking for communication with guest |
Hab an BookingNumber wie bei Booking gedacht mit Buchstaben und Zahlen

2024-05-14 19:27 UTC, StroSte commented on db-design.md
> +| RoomImageId | Int          | no   | autoincrement | PK                                   |
Wie in der Gruppe besprochen, aus diversen Gründen würde ich bei der schreibweise bleiben.

2024-05-14 19:27 UTC, StroSte commented on db-design.md
> +| CharacteristicId | Int         | no   | autoincrement | PK          |
Wie in der Gruppe besprochen, aus diversen Gründen würde ich bei der schreibweise bleiben.

2024-05-14 19:27 UTC, StroSte commented on db-design.md
> +| BookingId     | Int         | no       | autoincrement | PK                                                          |
Wie in der Gruppe besprochen, aus diversen Gründen würde ich bei der schreibweise bleiben.

2024-05-14 19:28 UTC, StroSte commented on db-design.md
> +| GuestId      | Int          | no       | autoincrement | PK                               |
Wie in der Gruppe besprochen, aus diversen Gründen würde ich bei der schreibweise bleiben.

2024-05-14 19:28 UTC, StroSte commented on db-design.md
> +| RoomId      | Int          | no   | autoincrement | PK                    |
Wie in der Gruppe besprochen, aus diversen Gründen würde ich bei der schreibweise bleiben.

2024-05-15 09:49 UTC, lukasfoidl approved these changes

2024-05-15 09:49 UTC, merged